services:
    postgres:
        image: postgres:latest
        container_name: movie-app-postgres
        environment: 
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        expose:
            - '5432:5432'
        volumes:
            - movie-app-pg_data:/var/lib/postgresql/data

    frontend:
        container_name: movie-app-frontend
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        expose:
            - "6901:6901"
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /frontend_src
                  ignore: 
                    - node_modules/

    backend:
        container_name: movie-app-backend
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
        expose:
            - "6900:6900"
        depends_on:
            - postgres
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /backend_src

    nginx:
        container_name: movie-app-nginx
        build: 
            context: ./nginx
            dockerfile: ./Dockerfile
        ports:
            - "1337:80"
        depends_on:
            - "backend"

volumes:
    movie-app-pg_data:
